services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: library-management-system
        container_name: library-management-system-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - library-management-system-net
    nginx:
        image: nginx:stable-bullseye
        container_name: library-management-system-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - library-management-system-net
    database:
        image: "postgres:15-bullseye"
        container_name: library-management-system-database
        ports:
            - "5432:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "library-management-system-database:/var/lib/postgresql/data"
        networks:
            - library-management-system-net
networks:
    library-management-system-net:
        driver: bridge
volumes:
    library-management-system-database:
        name: library-management-system-database-vol
        driver: local
